name: pullWorkflow

on:
  pull_request:
    branches: [master, dev]
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run lint
        run: npm run lint
      - name: testWithJest
        run: npm run test

  cypress-run:
    name: intergration-test
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: false
          start: npm run dev
          working-directory: ./
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
